### ISSUE TITLE
Is my Filterenvelope-Section wired?

### ISSUE THREAD

**Issue by johanekamp** [surge-synthesizer/monique-monosynth#102]
![Screenshot_20220529_164359](https://user-images.githubusercontent.com/106480794/170875415-f7de12ce-8492-409e-91a9-1b31c73e261e.png)

Hello, 
Just installed Monique, played around a bit, but noticed something strange:
The Envelope of the Filters has Attack-Slider two times, I think the last one should be a Release-Slider, right?

Is it the same for anyone else??
Kind regards, 
Jojo

**Comment by ghost** [comment]
oh yes.
thank you very much!
fixing in a minute.

**Comment by ghost** [comment]
Next nightly  which is up in 15-20 min  has it fixed.
Thanks again.

**Comment by johanekamp** [comment]
Thanks a lot!! Very nice!
