### ISSUE TITLE
xcode project or projucer file?

### ISSUE THREAD

**Issue by dataexcess** [surge-synthesizer/monique-monosynth#128]
Hello,

I followed the instructions command and I'm now left wondering how to open this in xcode? 
Is there a .projucer or.xcproj file somewhere generated? I cannot find it. Thank you!

**Comment by baconpaul** [comment]
We use cmake. You can make an Xcode project using cmake -GXcode in the first cmake step or build with any cmake aware tool or the command line

**Comment by dataexcess** [comment]
Thank you so much for the quick answer! 
I'm still realtively new to CMake so I didn't know about this -gxcode argument.

Ok, I reinstalled now with the extra argument and I found a xcodeproj in the /ignore/build folder.
I can open this project but I don't see the src folder in xcode.. is this normal? I am used to open juce xcode projects via the projucer and all the source files always have more or less the same folder structure. 
I also tried to run the MoniqueMonosynth_VST3 target (with ableton as exceutable) and it runs but I cannot find any monique synth in my plugin folder...

Any help much appreciated! Thank you!

**Comment by baconpaul** [comment]
I don’t use Xcode but the project should be complete 

the vst3 will be in ignore/build somewhere - would have to look but probably src/Monique artefacts or thereabouts 

If in the first cmake where you do -g Xcode you also add 

-DMONIQUE_COPY_PLUGIN_AFTER_BUILD=True 

The vat3 will install in ~library at the end of a successful build. The standalone target is also useful for testing

**Comment by dataexcess** [comment]
I found the VST3 and put it in my audio/plugins folder. 
All good, thank you!
