### ISSUE TITLE
Further repository organization

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/monique-monosynth#30]
All folders lowercase (to match Surge XT repo).

`Source` -> `src`
`Manual` -> `doc`
`Files`, `Fonts`, `Icon`, `Images`, `iPad`, `Spec` -> all move into `resources` (better name for `Spec` folder?)
Inside `Files` we have factory presets, move that to `resources/patches`
Inside `Files` we have factory themes, move that to `resources/themes`

Any .xcf (Sketch) files should be in `resources/assets`

**Comment by baconpaul** [comment]
Looking at the code, I am also wondering if the Source move we want to do to "src/core" and "src/ui" and have the header paths set properly for each and so on. That would separate the code so we could start building some unit tests around the core perhaps.
