### ISSUE TITLE
Better Installer than just a zip

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/monique-monosynth#39]
Right now we have two cmake targets, `monique-staged` which builds all the assets and copies them into a well known directory and `monique-installer` which zips that up with a version name.

So cool this is a placeholder issue, then, to do 'better than a zip' by adding the appropriate scripts and cmake rules to build

- [ ] an inno or msi type installer on windows
- [x] a signed dmg of a package on macos
- [ ] an rpm and deb on linux

**Comment by baconpaul** [comment]
for the signed dmg I have a script in the `sst-plugininfra` submodule. I would love to have an installer and rpm script there too so we can get consistent installer across monique and shortcircuit and so on.

**Comment by baconpaul** [comment]
and i just pushed that macOS change.

**Comment by mthierman** [comment]
I've kept the windows zip installer until pipelines can be updated etc.

I've used the same version method as the mac installer but maybe that should be updated to match Surge's method of env variable? That has never worked for me when building locally so I just copied the mac steps for now.
