### ISSUE TITLE
Patch browser not working in VST

### ISSUE THREAD

**Issue by mthierman** [surge-synthesizer/monique-monosynth#43]
Patch browser switches to Z bank when selecting a factory patch in VST version. Standalone does not have this issue.

OS: Windows 11
DAW: Reaper 6.42

![monique-patch](https://user-images.githubusercontent.com/68129072/145925240-eef8a8bf-ed20-44ec-b177-26f0f6cfdb00.gif)

**Comment by baconpaul** [comment]
i confirmed the same running the mac vst3 in bespoke

**Comment by baconpaul** [comment]
but it does not seem to do it with the mac au in logic. hmm.

**Comment by mthierman** [comment]
It also does it in bitwig but it's intermittent. In reaper A bank is default but in bitwig Z bank is the default.

**Comment by baconpaul** [comment]
I wonder if there’s a vst program change screwiness going on. Interesting

**Comment by TommmyArn** [comment]
A hotfix for: https://github.com/surge-synthesizer/monique-monosynth/pull/44
This fix disables Bank selects, and we can go on testing.

**Comment by mthierman** [comment]
Thanks for the fix!
