### ISSUE TITLE
Fix deprecated Bus apis

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/monique-monosynth#60]
Right now Monique uses the deprecated isChannelName apis and stuff.
My Clap wrapper assumes you are using the newer APIs and we should upgrade to proper bus apis anyway
so I'll do that one day to get sound as opposed to just param automation from monique :)

**Comment by ghost** [comment]
#96 is an attempt at this 
whether that change also helps towards clapification i could not test
due to lack of compatible host.
so @baconpaul whenever you have a minute to confirm (or deny)...

**Comment by baconpaul** [comment]
It does! Works perfectly. I'll send a PR to enable clap shortly
