### ISSUE TITLE
My virus software does not allow the file.

### ISSUE THREAD

**Issue by bearsdj** [surge-synthesizer/monique-monosynth#64]
Hi

My Norton 360 does not allow the files says its a trojan.
Name: Ws.reputation.1
Type: Trojan
Any ideas about this?

**Comment by baconpaul** [comment]
Hi!

the virus detectors do a poor job with infrequently used executables and we get positive scans on occasion. Surge and Monique use the same technique and here’s what we said about surge.

https://surge-synthesizer.github.io/viruses

our experience is after a formal release the virus scanners learn we are ok pretty quickly but the nightlies are a bit more likely to false positive 

I hope that helps!

**Comment by bearsdj** [comment]
Thanx for the help.
